#!/bin/bash
# Startup script for host2
# Generated by MRC emu topology generator

# Plane 0: eth1 -> p0-leaf2
ip -6 addr add fd00:0:22:ff::1/127 dev eth1
ip link set eth1 up
ip link set eth1 mtu 9216
ip -6 route add default via fd00:0:22:ff::0 dev eth1 metric 100

# Plane 1: eth2 -> p1-leaf2
ip -6 addr add fd00:1:22:ff::1/127 dev eth2
ip link set eth2 up
ip link set eth2 mtu 9216
ip -6 route add default via fd00:1:22:ff::0 dev eth2 metric 101

/usr/sbin/sshd
echo "Host configuration complete"
